name: perapera_trainer
description: >
  Allenamento verbi giapponesi in Flutter, con modalitÃ  CLI opzionale.
publish_to: 'none'
version: 1.2.0+12

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  in_app_purchase: ^3.1.13
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#1E1E1E"
  adaptive_icon_foreground: assets/app_icon.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/mascotte.png
    - assets/tierS.png
    - assets/tierA.png
    - assets/tierB.png
    - assets/tierC.png
    - assets/tierD.png
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Variable.ttf
